🚧 WIP

diff --git a/Dockerfile.dev b/Dockerfile.dev
--- a/Dockerfile.dev
+++ b/Dockerfile.dev
@@ -5,6 +5,22 @@ RUN apk add --no-cache libc6-compat
 RUN apk update && apk upgrade openssl
 WORKDIR /app
 
+# Install dependencies based on the preferred package manager
+
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml\* ./
+COPY ./patches ./patches
+
+RUN \
+ if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+ elif [ -f package-lock.json ]; then npm ci; \
+ elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm install --shamefully-hoist --strict-peer-dependencies=false --frozen-lockfile; \
+ else echo "Lockfile not found." && exit 1; \
+ fi
+
+##### BUILDER
+
+FROM --platform=linux/amd64 node:20-alpine3.19 AS builder
+
 ARG SESSION_SECRET
 ARG DATABASE_URL
 ARG GITHUB_CLIENT_ID
@@ -29,24 +45,6 @@ ENV REDIS_HTTP_USERNAME=$REDIS_HTTP_USERNAME
 ENV REDIS_HTTP_PASSWORD=$REDIS_HTTP_PASSWORD
 ENV KV_PREFIX=$KV_PREFIX
 
-
-# Install dependencies based on the preferred package manager
-
-COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml\* ./
-COPY ./patches ./patches
-
-RUN \
- if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
- elif [ -f package-lock.json ]; then npm ci; \
- elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm install --shamefully-hoist --strict-peer-dependencies=false --frozen-lockfile; \
- else echo "Lockfile not found." && exit 1; \
- fi
-
-##### BUILDER
-
-FROM --platform=linux/amd64 node:20-alpine3.19 AS builder
-ARG DATABASE_URL
-ARG NEXT_PUBLIC_CLIENTVAR
 WORKDIR /app
 COPY --from=deps /app/node_modules ./node_modules
 COPY . .
@@ -56,7 +54,7 @@ ENV NEXT_TELEMETRY_DISABLED 1
 RUN \
  if [ -f yarn.lock ]; then yarn build; \
  elif [ -f package-lock.json ]; then npm run build; \
- elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm run db:migrate-docker && pnpm run build; \
+ elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm run build; \
  else echo "Lockfile not found." && exit 1; \
  fi
 
@@ -64,6 +62,30 @@ RUN \
 
 FROM --platform=linux/amd64 node:20-alpine3.19 AS runner
 WORKDIR /app
+
+ARG SESSION_SECRET
+ARG DATABASE_URL
+ARG GITHUB_CLIENT_ID
+ARG GITHUB_SECRET
+ARG GITHUB_PERSONAL_ACCESS_TOKEN
+ARG KV_PREFIX
+ARG NEXT_PUBLIC_VERCEL_URL="localhost:3000"
+ARG REDIS_HTTP_URL="http://webdis:7379"
+ARG REDIS_HTTP_USERNAME="user"
+ARG REDIS_HTTP_PASSWORD="password"
+ARG GITHUB_REDIRECT_URI="http://localhost:3000/api/auth/callback"
+
+ENV NEXT_PUBLIC_VERCEL_URL=$NEXT_PUBLIC_VERCEL_URL
+ENV SESSION_SECRET=$SESSION_SECRET
+ENV DATABASE_URL=$DATABASE_URL
+ENV GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
+ENV GITHUB_REDIRECT_URI=$GITHUB_REDIRECT_URI
+ENV GITHUB_SECRET=$GITHUB_SECRET
+ENV GITHUB_PERSONAL_ACCESS_TOKEN=$GITHUB_PERSONAL_ACCESS_TOKEN
+ENV REDIS_HTTP_URL=$REDIS_HTTP_URL
+ENV REDIS_HTTP_USERNAME=$REDIS_HTTP_USERNAME
+ENV REDIS_HTTP_PASSWORD=$REDIS_HTTP_PASSWORD
+ENV KV_PREFIX=$KV_PREFIX
 
 ENV NODE_ENV production
 
